# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            cd tradespace_backend
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            cd tradespace_backend
            . venv/bin/activate
            chmod +x gen_firebase_keys_from_envvar.sh ./gen_twilio_keys_from_envvar.sh
            ./gen_firebase_keys_from_envvar.sh > instance/tradespace_firebase_admin_key.json
            ./gen_twilio_keys_from_envvar.sh > instance/TwilioKeys.py
            pytest

      - store_artifacts:
          path: test-reports
          destination: test-reports
  deploy:
    docker:
        # specify the version you desire here
        - image: circleci/python:3.6.1-node

    working_directory: ~/repo

    steps:
        - checkout
        - add_ssh_keys:
            fingerprints:
              - "81:6e:bb:4c:4f:4e:33:ae:a6:d2:93:73:c7:5d:8a:3c"
        - run:
            name: Install firebase-tools
            command: |
                curl -sL firebase.tools | bash

        - run:
            name: Backend Deployment over SSH
            command: |
                ssh-keyscan -H api.tradespace.store >> ~/.ssh/known_hosts
                ssh ec2-user@api.tradespace.store "./TradeSpace/tradespace_backend/deploy.sh"

        - run:
            name: Frontend Deployment using Firebase
            command: |
                cd tradespaceui/
                npm run build
                firebase deploy


workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: backend_secrets
      - deploy:
          context: backend_secrets
          requires:
            - build
          filters:
            branches:
                only: master
